### ISSUE TITLE
upgrade to latest Spring Boot 2

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/ci-droid#16]
Spring Boot 2 is now mature, so we should target to migrate towards it

**Comment by oterrien** [comment]
Ci-droid is going to become reactive ?

**Comment by vincent-fuchs** [comment]
> Ci-droid is going to become reactive ?

Not for now, this issue is more to make sure we keep up with Spring Boot versions and don't lag behind too much. 

However, we have the plan to maybe deploy CI-droid publicly at some point in time, for people to make bulk updates on their github repos. If we reach that stage, maybe the reactive approach will be useful, to report the action status back to the UI, instead of sending notifications by emails like today.

Let me know if you're interested in taking up this issue ;-) it's not too complicated, we did for Github crawler some time back : 

https://github.com/societe-generale/github-crawler/commit/e18a4ab7054731f4d8e9d51442b3ca7074bb5b8e

**Comment by vincent-fuchs** [comment]
done here for tasks consumer : https://github.com/societe-generale/ci-droid-tasks-consumer/commit/354c2aff7b9bec41acfa0c6ac4725a759b3e8cce
