### ISSUE TITLE
from UI, all resourcesToUpdate are sent to backend, even if not selected

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/ci-droid#34]
**Describe the bug**

in CI-droid UI, I upload a file with a couple of resources to update. I select only one of them but all are sent to backend for processing.

**Expected behavior**

only the ones selected should be sent for processing

**Additional context**

happening on https://github.com/societe-generale/ci-droid/commit/856bb26226b91dcbebb66d6be3ddd70212fc163f

**Comment by paul58914080** [comment]
@J-DK is working on this.

**Comment by J-DK** [comment]
@vincent-fuchs @paul58914080 Hi, I have created a PR fixing this bug.
