### ISSUE TITLE
ci-droid unable to raise pull request with special character / on branch name

### ISSUE THREAD

**Issue by paul58914080** [societe-generale/ci-droid#47]
**Describe the bug**

When we raise a pr with the branch name containing /, ci droid is able to create a branch and commit the changes but is unable to raise a pull request.

**Expected behavior**

It should be able to create pull request even with /

**Comment by vincent-fuchs** [comment]
I am not sure I am able to reproduce. I remember seeing a response code 422 when we looked at it together. Now the only time I am able to get a 422 at pull request creation time is when I try to create a PR on a branch that is even with master, ie no change in the branch. 

Can you try to reproduce please ? and send me the logs by email please

**Comment by paul58914080** [comment]
@vincent-fuchs we will close this for now as I couldn't reproduce it as well. If this happens again I will re-open this issue along with the steps to re-produce.
